### ISSUE TITLE
Support predicate pushdown for partitioned table

### ISSUE THREAD

**Issue by ly9chee** [apache/incubator-paimon-trino#11]
## Description
When executing a query with a partition key filter, there is no effect of predicate pushdown, the ScanFilter operator still performs a full table scan.

paimon version: 0.4
trino version: 412

**Comment by JingsongLi** [comment]
@ly9chee thanks for reporting. Can you show the sql?

**Comment by ly9chee** [comment]
sure, bellow are the steps to reproduce:
#### create a partition table
```sql
CREATE TABLE `activity_daily` (
  `dt` CHAR(10) NOT NULL,
  `tenant_id` STRING NOT NULL,
  `order_count` BIGINT,
  PRIMARY KEY (`dt`, `tenant_id`) NOT ENFORCED
) PARTITIONED BY (`dt`)
WITH (
  'bucket' = '1',
  'bucket-key' = 'tenant_id'
);
```
#### write some test data
```sql
INSERT OVERWRITE `activity_daily` (`dt`, `tenant_id`, `order_count`) VALUES
    ('2023-06-01', '001', 1),
    ('2023-06-02', '001', 20),
    ('2023-06-02', '002', 5),
    ('2023-06-03', '002', 3),
    ('2023-06-04', '003', 6),
    ('2023-06-05', '001', 2),
    ('2023-06-05', '002', 3);
```
#### (trino) query this table with a filter key
```sql
select * from activity_daily where dt = '2023-06-02';
```

<img width="1114" alt="image" src="https://github.com/apache/incubator-paimon-trino/assets/54972801/2c4e8163-ba57-4fcd-a336-3058d8aa0f7a">
