### ISSUE TITLE
Timestamp type resolved incorrectly when create (or show the table structure ) of a paimon catalog table in trino

### ISSUE THREAD

**Issue by jjrrzxc** [apache/incubator-paimon-trino#28]
eg: 
create ddl:
CREATE TABLE sales_order_line (
  seq_id BIGINT,
  id VARCHAR(2147483647),
  tenant_id VARCHAR(2147483647),
  biz_time TIMESTAMP(0),
  organization_id VARCHAR(2147483647),
  extend_create_info VARCHAR(2147483647),
  extend_modify_info VARCHAR(2147483647),
  order_id VARCHAR(2147483647),
  line_type VARCHAR(2147483647),
  root_line_id VARCHAR(2147483647),
  parent_line_id VARCHAR(2147483647),
  customer_id VARCHAR(2147483647),
  line_index VARCHAR(2147483647),
  quantity INT,
  total_retail_amount DECIMAL(25, 2),
  total_transaction_amount DECIMAL(25, 2),
  discount DECIMAL(25, 2),
  arrears_amount DECIMAL(25, 2),
  arrears_clear_amount DECIMAL(25, 2),
  product_id VARCHAR(2147483647),
  product_name VARCHAR(2147483647),
  product_type VARCHAR(2147483647),
  note VARCHAR(2147483647),
  origin_item_id VARCHAR(2147483647),
  expire_date TIMESTAMP(0),
  sales_item_snapshot_id VARCHAR(2147483647),
  redeems VARCHAR(2147483647),
  deleted TINYINT,
  version INT,
  create_by VARCHAR(2147483647),
  create_time TIMESTAMP(0),
  modify_by VARCHAR(2147483647),
  modify_time TIMESTAMP(0),
  leaf TINYINT
) WITH (
    file_format = 'ORC',
    primary_key = ARRAY['seq_id','biz_time'],
    partitioned_by = ARRAY['biz_time'],
    bucket = '3',
    bucket_key = 'seq_id',
    changelog_producer = 'input',
    path='oss://lc-bigdata/store/testdb.db/sales_order_line'
)

the real paimon table structure is :
{
  "id" : 0,
  "fields" : [ {
    "id" : 0,
    "name" : "seq_id",
    "type" : "BIGINT NOT NULL"
  }, {
    "id" : 1,
    "name" : "id",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 2,
    "name" : "tenant_id",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 3,
    "name" : "biz_time",
    "type" : "TIMESTAMP(6) NOT NULL"
  }, {
    "id" : 4,
    "name" : "organization_id",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 5,
    "name" : "extend_create_info",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 6,
    "name" : "extend_modify_info",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 7,
    "name" : "order_id",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 8,
    "name" : "line_type",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 9,
    "name" : "root_line_id",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 10,
    "name" : "parent_line_id",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 11,
    "name" : "customer_id",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 12,
    "name" : "line_index",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 13,
    "name" : "quantity",
    "type" : "INT"
  }, {
    "id" : 14,
    "name" : "total_retail_amount",
    "type" : "DECIMAL(25, 2)"
  }, {
    "id" : 15,
    "name" : "total_transaction_amount",
    "type" : "DECIMAL(25, 2)"
  }, {
    "id" : 16,
    "name" : "discount",
    "type" : "DECIMAL(25, 2)"
  }, {
    "id" : 17,
    "name" : "arrears_amount",
    "type" : "DECIMAL(25, 2)"
  }, {
    "id" : 18,
    "name" : "arrears_clear_amount",
    "type" : "DECIMAL(25, 2)"
  }, {
    "id" : 19,
    "name" : "product_id",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 20,
    "name" : "product_name",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 21,
    "name" : "product_type",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 22,
    "name" : "note",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 23,
    "name" : "origin_item_id",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 24,
    "name" : "expire_date",
    "type" : "TIMESTAMP(6)"
  }, {
    "id" : 25,
    "name" : "sales_item_snapshot_id",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 26,
    "name" : "redeems",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 27,
    "name" : "deleted",
    "type" : "TINYINT"
  }, {
    "id" : 28,
    "name" : "version",
    "type" : "INT"
  }, {
    "id" : 29,
    "name" : "create_by",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 30,
    "name" : "create_time",
    "type" : "TIMESTAMP(6)"
  }, {
    "id" : 31,
    "name" : "modify_by",
    "type" : "VARCHAR(2147483646)"
  }, {
    "id" : 32,
    "name" : "modify_time",
    "type" : "TIMESTAMP(6)"
  }, {
    "id" : 33,
    "name" : "leaf",
    "type" : "TINYINT"
  } ],
  "highestFieldId" : 33,
  "partitionKeys" : [ "biz_time" ],
  "primaryKeys" : [ "seq_id", "biz_time" ],
  "options" : {
    "bucket" : "3",
    "path" : "oss://lc-bigdata/store/testdb.db/sales_order_line",
    "bucket-key" : "seq_id",
    "changelog-producer" : "input",
    "file.format" : "orc"
  },
  "timeMillis" : 1694140846488
}

 we can see TIMESTAMP(0) datatype converted to TIMESTAMP(6), 
and when show this table in trino:
<img width="451" alt="image" src="https://github.com/apache/incubator-paimon-trino/assets/35166606/f61d0af8-735b-41ea-86c8-970afb78d9e9">

timestamp(6) saved in paimon schema converted to timestamp(3) in trino schema.
schema unaligned between engine and storage may cause some unpredictable problems，it should be resolved.

**Comment by jjrrzxc** [comment]
found a new problem "Unhandled type for long: timestamp(0)",i will fix it

**Comment by gfunc** [comment]
got a similar problem trying out 0.6-snapshot `Unhandled type for long: timestamp(3) with time zone`. guess could fix by similar approach

**Comment by jjrrzxc** [comment]
more over,BlockBuilder beginEntry/closeEntry  is deprecated in trino 422,so the unit test will run failed,  i will update beginEntry/closeEntry with buildEntry in ComplexTypes query based on trino 422

**Comment by gfunc** [comment]
I also had a run for unit tests for 422. 
first I added below to pom.xml to avoid surefire error
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>--add-opens=java.base/java.nio=ALL-UNNAMED</argLine>
                </configuration>
            </plugin>
```
tests for 422 are failing because

1.  airlift configuration dependency version (maybe should use 234 instead of 216?)
2.  airlift slice version (0.42 -> 0.46)
3.  SPI beginEntry/closeEntry problem.

**Comment by gfunc** [comment]
> I also had a run for unit tests for 422. first I added below to pom.xml to avoid surefire error
> 
> ```
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-surefire-plugin</artifactId>
>                 <configuration>
>                     <argLine>--add-opens=java.base/java.nio=ALL-UNNAMED</argLine>
>                 </configuration>
>             </plugin>
> ```
> 
> tests for 422 are failing because
> 
> 1. airlift configuration dependency version (maybe should use 234 instead of 216?)
> 2. airlift slice version (0.42 -> 0.46)
> 3. SPI beginEntry/closeEntry problem.

sorry for having missed out on the commit. Guess these are all fixed.
