### ISSUE TITLE
TrinoSplitManagerBase's single read batch is too large

### ISSUE THREAD

**Issue by groobyming** [apache/incubator-paimon-trino#37]
The nextPage method of TrinoPageSourceBase reads a batch of data each time. Through debugging, I found that the batch is very large, which leads to the use of DynamicSliceOutput.writeBytes of a VariableWidthBlockBuilder object when processing strings. String writing will cause the size attribute to continue to expand and eventually exceed the maximum value of int and overflow.
debug code：
<img width="647" alt="image" src="https://github.com/apache/incubator-paimon-trino/assets/34335395/b28888ba-7d80-41ac-82a8-d06c7c088d50">

batch size print：
<img width="1340" alt="image" src="https://github.com/apache/incubator-paimon-trino/assets/34335395/10dcceab-948a-46e6-987e-46da382b9d47">

Exception occurrence code：
<img width="747" alt="image" src="https://github.com/apache/incubator-paimon-trino/assets/34335395/c4f875b3-fd1a-48a3-b403-5bf6e5be8e27">

<img width="1075" alt="image" src="https://github.com/apache/incubator-paimon-trino/assets/34335395/3d096614-1590-4bb2-9dc2-4790ae23402b">

**Comment by groobyming** [comment]
@JingsongLi jin

**Comment by JingsongLi** [comment]
Thanks @groobyming 
Already fixed.
